#!/bin/bash

RRIKDIR=/home/will/Research/Projects/RRIkinetics/RRIKin
TDIR=$RRIKDIR/Test
TFILE=$TDIR/dimer

COMMON_OPTS=""
COMMON_OPTS="$COMMON_OPTS --max-hyb-length 10"
ENUM_OPTS="--max-hyb-length-diff 5 --max-total-energy 10"

seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAG
#seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAG
#seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGACAGAUACUAGUUUCAAAACUUCCUUGACAGAACCAUUUCAUGUUCAAUAAUGAAAAUUACUUUCACAUGUUUUAGUGGAAAACGUACGUACGUAUCGUAGCGGUUGGACUUACGUAUAC

seqB=GCUGCGAUGCAUGCCUCGAU
#seqB=GCUGCGAUGCAUGCCUCGAUAUGCCUCGAUAUGCCUCGAU
#seqB=GCUGCGAUGCAUGCCUCGAUAUGCCUCGAUAUGCCUCGAUGUAAAAAUUAAAAAAAUAUAAUACAUUAAAUGCAAAAUAAGUUUAGCUUACGGUACGUAG

# ## SY2808 suffix
# seqA=CAGATACTAGTTTCAAAACTTCCTTGACAGAACCATTTCATGTTCAATAATGAAAATTACTTTCACATGTTTTAGTGGAAAAATACTGAACAATGAAATTTCAATATCGCATATAATAATTTTTGTTATCAAATATATATTTTTCGGAAGTCATATACATTAAATAATTAAAACATTATTTTTAAAAATTAAAAAAATAT
# seqA=TGAAAATTACTTTCACATGTTTTAGTGGAAAAATACTGAACAATGAAATTTCAATATCGCATATAATAATTTTTGTTATCAAATATATATTTTTCGGAAGTCATATACATTAAATAATTAAAACATTATTTTTAAAAATTAAAAAAATAT

# ## SY6022 prefix
# seqB=GAAATTTCAATATCGCATATAATAATTTTTGTTATCAAATATATATTTTTCGGAAGTCATATACATTAAATAATTAAAACATTATTTTTAAAAATTAAAAAAATATATTTTAGCAAATAGTTTTTACTTTTTTTTAAATGCAAAATAAGTTCACGTGATATTATTAATAATATTTTACCCAAAAATATGAGGGCATCGGA
# seqB=GAAATTTCAATATCGCATATAATAATTTTTGTTATCAAATATATATTTTTCGGAAGTCATATACATTAAATAATTAAAACATTATTTTTAAAAATTAAAAAAATATATTTTAGCAAATAGTTTTTACTTTTTTTTAAATGCAAAATAAGT

## nette Beispiele:
# competing sites
#seqA=AAAGGGGGGAAAAAAAGGGUGGGAAAAAAAGGGCGGGAAA
#seqB=CCCGCCC


function call {
    echo $*
    time $*
}

function call_redirect {
    tgt=$1
    shift 1
    echo $* \> $tgt
    time $* > $tgt
}

call $RRIKDIR/src/rrikin_enum $seqA $seqB >$TFILE --no-double  --verbose $ENUM_OPTS $COMMON_OPTS

sort -g -k1 $TFILE > $TFILE.s

call $RRIKDIR/src/rrikin_barriers $seqA $seqB <$TFILE.s -o $TFILE.bg --no-double --verbose  $COMMON_OPTS

call_redirect $TFILE.out $RRIKDIR/src/rrikin_prune $TFILE.bg --pffile $TFILE.pf --max-out 0.05 --min-rate 1e-5 --min-p-equ 1e-22 --verbose

call src/xrates.m $TFILE.pf --out $TFILE.kin --t8 1e15

call Rscript $RRIKDIR/src/kinetics.R $TFILE.kin $TDIR/kinetics.pdf
