#!/bin/bash

RRIKDIR=/home/will/Research/Projects/RRIkinetics/RRIKin
TDIR=$RRIKDIR/Test
TFILE=$TDIR/dimer

COMMON_OPTS=""
COMMON_OPTS="$COMMON_OPTS --max-hyb-length-diff 8 --span=100 --regionA -100 --regionB 30" #  --max-hyb-length 8
ENUM_OPTS="--max-hyb-energy 6 --max-total-energy 10"

#seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAG
#seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAG
seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGACAGAUACUAGUUUCAAAACUUCCUUGACAGAACCAUUUCAUGUUCAAUAAUGAAAAUUACUUUCACAUGUUUUAGUGGAAAACGUACGUACGUAUCGUAGCGGUUGGACUUACGUAUAC

seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGACAGAUACUAGUUUCAAAACUUCCUUGACAGAACCAUUUCAUGUUCAAUAAUGAAAAUUACUUUCACAUGUUUUAGUGGAAAACGUACGUACGUAUCGUAGCGGUUGGACUUACGUAUACCGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGACAGAUACUAGUUUCAAAACUUCCUUGACAGAACCAUUUCAUGUUCAAUAAUGAAAAUUACUUUCACAUGUUUUAGUGGAAAACGUACGUACGUAUCGUAGCGGUUGGACUUACGUAUAC

#seqB=GCUGCGAUGCAUGCCUCGAU
#seqB=GCUGCGAUGCAUGCCUCGAUAUGCCUCGAUAUGCCUCGAU
seqB=GCUGCGAUGCAUGCCUCGAUAUGCCUCGAUAUGCCUCGAUGUAAAAAUUAAAAAAAUAUAAUACAUUAAAUGCAAAAUAAGUUUAGCUUACGGUACGUAG


## nette Beispiele:
# competing sites
#seqA=AAAGGGGGGAAAAAAAGGGUGGGAAAAAAAGGGCGGGAAA
#seqB=CCCGCCC

## starker decoy state
#seqA=CGGAGCGACGCUACGUACGGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGAGCUAGCUGAAACGUAGCAGACAGAUACUAGUUUCAAAACUUCCUUGACAGAACCAUUUCAUGUUCAAUAAUGAAAAUUACUUUCACAUGUUUUAGUGGAAAACGUACGUACGUAUCGUAGCGGUUGGACUUACGUAUAC
#seqB=GCUGCGAUGCAUGCCUCGAU


function call {
    echo
    echo $*
    $*
}

function tcall {
    echo
    echo $*
    time $*
}

function call_redirect {
    tgt=$1
    shift 1
    echo
    echo $* \> $tgt
    $* > $tgt
}

call_redirect $TFILE $RRIKDIR/_inst/bin/rikin_enum $seqA $seqB --no-double --verbose $ENUM_OPTS $COMMON_OPTS

LC_ALL=C sort -g -k1 $TFILE > $TFILE.s

call $RRIKDIR/_inst/bin/rikin_barriers $seqA $seqB -i $TFILE.s -o $TFILE.bg --track $TFILE.barriers_track.gz --no-double --verbose $COMMON_OPTS

# call_redirect $TFILE.out $RRIKDIR/_inst/bin/rikin_prune $TFILE.bg --pffile $TFILE.pf  --min-rate 1e-10 --num-out 50 --num-pequ 100 --track $TFILE.prune_track.gz --verbose --barfile $TFILE.bar --ratesfile $TFILE.rates

call_redirect $TFILE.out $RRIKDIR/_inst/bin/rikin_prune $TFILE.bg --pffile $TFILE.pf  --min-rate 1e-7 --num-out 10 --num-pequ 60 --track $TFILE.prune_track.gz --verbose --barfile $TFILE.bar --ratesfile $TFILE.rates


tcall $RRIKDIR/_inst/bin/xrates.m $TFILE.pf --out $TFILE.kin --t8 1e15 --mfpts

call Rscript $RRIKDIR/_inst/bin/kinetics.R $TFILE.kin 
