#!/usr/bin/env perl

=head1 run_all

run_all

=head1 SYNOPSIS

run_all [options]

=head1 DESCRIPTION

Run kinetics calculations for pairs in table SI_Tab4.txt subject to
filter criteria (see constants in code.)

=head1 OPTIONS

=over 8

=item  B<--help>

Brief help message

=item  B<--man>                         

Full documentation

=item B<--dry>

Dry run. Test only.

=item  B<-q, --quiet>

Quiet

=item  B<-v, --verbose>

Verbose

=back

=cut


use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin;


##----------------------------------------
## subs
sub min($$) {
    my ($x,$y)=@_;
    return ($x<=$y)?$x:$y;
}
sub max($$) {
    my ($x,$y)=@_;
    return ($x>=$y)?$x:$y;
}

sub writecmd($$$) {
    my ($fh,$cmd,$active)=@_;
    
    if (!$active) {
	print $fh "# ";
    }
    print $fh $cmd;
}

##------------------------------------------------------------
## options

use Getopt::Long;
use Pod::Usage;

my $help;
my $man;
my $quiet;
my $verbose;

my $dry=0;

GetOptions(
    "dry" => \$dry,
    "verbose" => \$verbose,
    "quiet" => \$quiet,   
    "help"=> \$help,
    "man" => \$man
    ) || pod2usage(2);

pod2usage(1) if $help;
pod2usage(-exitstatus => 0, -verbose => 2) if $man;

if (@ARGV!=1) {
    print "Name of parameter file is missing.\n";
    exit -1;
}

my $paramfile=$ARGV[0];

## ------------------------------------------------------------
## parameter default values

my $maxovsize=160;   ## filter instances by maximum overlap size
my $seqlength=100000; ## crop sequences to this length (use something
		     ## large to use full sequences)

## parameters of rrikin_enum/barriers
my $max_hyb_length_diff = 7;
my $region              = 180; ## if region_factor is defined then the region is computed!
my $region_factor       = 1.2; ## region=overlap*region_factor 
my $span                = 200;


my $datadir=$ENV{HOME}."/Research/Projects/RRIkinetics/YeastAntisense";

my $pairtab_filename="$datadir/SI_Tab4.txt";
my $seqtab_filename="$datadir/SI_Tab2.txt";
my $sequences_filename="$datadir/SI_Tab2-seqs.fa"; ## simple fasta of sequences

## whether to skip certain stages, if files exist
my $skip_enum=1; ## whether to skip state enumeration
my $skip_barriers=1; ## whether to skip basin constructions (barriers) 
my $skip_pruning=1; ## whether to skip pruning
my $skip_kin=1;  ## whether to skip kinetics calculation by call to xrates
my $skip_pdf=1;  ## whether to skip call to R and pdf generation

my $RRIKDIR;
BEGIN {
    $RRIKDIR=$ENV{HOME}."/Research/Projects/RRIkinetics/RRIKin";
}
use lib "$RRIKDIR/scripts";

my $outdir="/scr/k61san/will/RRIKin/Results/results";

my $ENUM_OPTS="--max-hyb-energy 7 --max-total-energy 12";
my $MIN_RATE=5e-12;
my $NUM_OUT=1500;
my $NUM_PEQU=6000;
my $QU_PEQU=35;
my $QU_OUT=8;

my $num_threads=48;

## ------------------------------------------------------------
## read in parameter file and evaluate;
## this allows to overwrite the default parameters
## ATTENTION: the paramfile is evaluated as perl code. Thus it could
## run anything, not only set parameters.
##
my $paramfilecontent="";
my $paramfh;
open($paramfh,$paramfile) || die "Cannot read parameter file $paramfile.\n";
while(<$paramfh>) {
    $paramfilecontent.=$_;
}
close $paramfh;

eval $paramfilecontent;

if ($@) {
    print STDERR "$@";
    exit -1;
} else {
    print "Read parameters from $paramfile.\n";
}

## ------------------------------------------------------------
my $COMMON_OPTS=
    "--max-hyb-length-diff $max_hyb_length_diff "
    ."--span $span ";
  ##  --max-hyb-length 50 (use only with state recovery!)


## ------------------------------------------------------------
## main part

use RRIkin;



my %sequences; ## hash of sequences by name

## read sequences (simple fasta format)
open(IN,$sequences_filename) || die "Cannot read input file $sequences_filename.\n";
while(<IN>) {
    if (/^>\s*(.*)/) {
	$sequences{$1}=<IN>;
    }
}
close IN;

mkdir "$outdir" unless $dry;
print "mkdir \"$outdir\"\n" if $dry;

system "cp $0 $outdir" unless $dry;
system "cp $paramfile $outdir/$0.params" unless $dry;

my $logfile="$outdir/README";
my $logfh;
$logfh=*STDOUT if $dry;
open($logfh,">>$logfile") unless $dry;

print $logfh "run_all: RRIkinetics calculations for RNA antisense pairs .\n";
print $logfh "START ".readpipe("date")."\n";
print $logfh "Saved copy of script 'run_all' and parameter file '$paramfile' in $outdir.\n";

close $logfh unless $dry;

## read pairs table
my $pairtab=read_table("$pairtab_filename");

## read sequence table
my $seqtab=read_table("$seqtab_filename");

my $joblistfh;
if (!$dry) {
    open($joblistfh,">$outdir/joblist") || die "Cannot open job file $outdir/joblist for output.";
} else {
    $joblistfh=*STDOUT;
}

my @jobs=();

## iterate over pairtab
for my $row (@$pairtab) {
    my $name1=$row->{"seg1.id"};
    my $name2=$row->{"seg2.id"};

    my $jobname="$name1-$name2";

    my $seqrow1 = lookup_table($seqtab,"tx_ID",$name1);
    my $seqrow2 = lookup_table($seqtab,"tx_ID",$name2);

    my $overlap = $seqrow1->{"last"} - $seqrow2->{"first"};
    
    # filter instances
    next if ($overlap > $maxovsize); 
    
    # compute region
    if (defined($region_factor)) {
	$region=int($region_factor*$overlap);
    }
    my $local_common_opts=$COMMON_OPTS." --regionA -$region --regionB $region ";
    
    my $cor = sprintf "%0.2f", $row->{"cor"};

    
    my $header = "$name1 $name2 $cor; ";
    #print "\t".$sequences{$name1}."\n";
    #print "\t".$sequences{$name2}."\n";
    
    $header.= "pos1: ".$seqrow1->{"first"}."-".$seqrow1->{"last"}.
	" ".$seqrow1->{"strand"}.
	"; pos2: ".$seqrow2->{"first"}."-".$seqrow2->{"last"}.
	" ".$seqrow2->{"strand"}."; ";

    $header.= "len1=".($seqrow1->{"last"} - $seqrow1->{"first"}).
	   "; len2=".($seqrow2->{"last"} - $seqrow2->{"first"}).
	   "; overlap=".$overlap.
	   "\n";

    my $seqA;
    my $seqB;

    # distinguish cases: "left" sequence on + strand and "right" on - strand, or vice versa.
    if ($seqrow1->{"strand"} eq "+") {
	$seqA=$sequences{$name1};
	$seqA=substr($seqA,-min(length($seqA),$seqlength));
	$seqB=$sequences{$name2};
	$seqB=substr($seqB,-min(length($seqB),$seqlength));
	chomp $seqA;
	chomp $seqB;
	$seqB=reverse $seqB;
    } else {
	$seqA=$sequences{$name1};
	$seqA=substr($seqA,0,min(length($seqA),$seqlength));
	$seqB=$sequences{$name2};
	$seqB=substr($seqB,0,min(length($seqB),$seqlength));
	chomp $seqA;
	chomp $seqB;
	$seqA=reverse $seqA;
    }

    my $rc_seqB=rev_compl($seqB);

    #print $sequences{$name1};
    #print $sequences{$name2};
    

    $header.= $seqA."\n";
    $header.= (" "x(length($seqA)-$overlap)).$seqB."\n";
    #print $rc_seqB."\n";
    
    print $header if ($verbose && !$dry);

    my $outfn="$outdir/$jobname";
    
    my $jobfh;
    if (!$dry) {
	open($jobfh,">$outfn.job") || die "Cannot open job file $outfn.job for output."; 
    } else {
	$jobfh=*STDOUT;
	
	print "\n-------------------------------------------------- file: $outfn.job\n";
    }

    my $comment_header;
    ($comment_header = $header) =~ s/\n/\n## /g;

    print $jobfh "## $comment_header\n\n";

    print $jobfh "seqA=$seqA\n\n";
    print $jobfh "seqB=$seqB\n\n";

    my $active;
    writecmd $jobfh,"echo START: `date` >>$outfn.prt\n\n",1;
    
    $active=!($skip_enum && (-e "$outfn.senum.gz" || -e "$outfn.senum"));
    writecmd $jobfh,"echo ENUM >>$outfn.prt\n\n",$active;
    writecmd $jobfh,"$RRIKDIR/src/rrikin_enum \$seqA \$seqB --no-double ".
	"--verbose $ENUM_OPTS $local_common_opts > $outfn.enum 2>>$outfn.prt\n\n",$active;
    writecmd $jobfh,"sort -g -k1 $outfn.enum > $outfn.senum\n",$active;
    writecmd $jobfh,"rm $outfn.enum\n\n",$active;

    $active=(!$skip_barriers || (! -e "$outfn.bar.gz" && ! -e "$outfn.bar"));
    writecmd $jobfh,"echo BARRIERS >>$outfn.prt\n\n",$active;
    writecmd $jobfh,"if [ ! -e \"$outfn.senum\" ]; then gunzip -f $outfn.senum.gz; fi\n",$active;
    writecmd $jobfh,"$RRIKDIR/src/rrikin_barriers \$seqA \$seqB -i $outfn.senum ".
	"-o $outfn.bar --track $outfn.bartrack.gz --no-double ".
	"--verbose $local_common_opts &>>$outfn.prt\n\n",$active;
    writecmd $jobfh,"gzip -f $outfn.senum\n",$active;

    $active=(!$skip_pruning || (! -e "$outfn.pf"));
    writecmd $jobfh,"echo PRUNE >>$outfn.prt\n\n",$active;
    writecmd $jobfh,"if [ ! -e \"$outfn.bar\" ]; then gunzip -f $outfn.bar.gz; fi\n",$active;
    writecmd $jobfh,"$RRIKDIR/src/rrikin_prune $outfn.bar --pffile $outfn.pf  --min-rate $MIN_RATE --num-out $NUM_OUT --num-pequ $NUM_PEQU --qu-out $QU_OUT --qu-pequ $QU_PEQU --track $outfn.prunetrack.gz --verbose --barfile $outfn.bar_prune --ratesfile $outfn.rates.gz > $outfn.prune_out 2>>$outfn.prt\n\n",$active;

    $active=(!$skip_kin || (! -e "$outfn.kin"));
    writecmd $jobfh,"echo XRATES >>$outfn.prt\n\n",$active;
    writecmd $jobfh,"$RRIKDIR/src/xrates.m $outfn.pf --out $outfn.kin --t8 1e16 &>>$outfn.prt\n\n",$active;
    
    $active=(!$skip_pdf || (! -e "$outfn.pdf"));
    writecmd $jobfh,"echo KINETICS >>$outfn.prt\n\n",$active;
    writecmd $jobfh,"Rscript $RRIKDIR/src/kinetics.R $outfn.kin $outfn.pdf 'cor=$cor; ol=$overlap' >$outfn.scores 2>>$outfn.prt\n",$active;
    
    writecmd $jobfh,"echo FINISH: `date` >>$outfn.prt\n\n",1;

    close $jobfh unless $dry;
    print "-------------------------------------------------- eof\n\n" 
	if $dry;
    
    print "Write to joblist: " if ($dry);

    print $joblistfh "$outfn.job\n";
    
    system("chmod +x $outfn.job") unless $dry;
    
    push @jobs,"$outfn.job"; 
}

print "\nGenerated ".int(@jobs)." jobs.\n" unless $quiet;

my $cmd="parallel -j $num_threads < $outdir/joblist";

open($logfh,">>$logfile") unless $dry;
print $logfh "\nCALL: $cmd\n";
close $logfh unless $dry;

if (!$dry) { 
    close $joblistfh;
    system("chmod +x $outdir/joblist");
    
    system $cmd;
}

open($logfh,">>$logfile") unless $dry;
print $logfh "FINISHED ".readpipe("date")."\n";
close $logfh unless $dry;


## ------------------------------------------------------------
